import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"
const font = Inter({
  weight:["400"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${font.className} bg-[url(/ai-generated-8540917.jpg)] bg-cover bg-center bg-no-repeat backdrop-blur-lg`}
      >
        {children}
        
      </body>
    </html>
  );
}
